version: 0.1.1
env:
  - JENKINS_NODE_WIN: "Dynamo_Win_003"
  - SLACK_QUANTUM_BUILD_CHANNEL : "#dynamo-jenkinsbuild"
  - SLACK_QUANTUM_BUILD_CREDENTIAL_ID : "slack-notify-token"
  - MAIL_QUANTUM_BUILD_RECIPIENT : "dynamo.dev@autodesk.com"
  - DOCKER_WORKSPACE : "c:\\Greg"
  - COMMON_TOOLS_DIR : "cicdscripts\\tools"
  - NUGETTOOL : "Nuget\\nuget.exe"
  - DOCKER_CONTAINER : "buildContainer"
  
check_changelog_updated_on_pr: false
pipeline_os: "Windows"
force_slack_notification : true
language: csharp

schedule:
  cron_schedule: "once_a_month"

jenkins_creds:
    -
      type: secretText
      credentialsId: dynamovisualprogramming_nuget_api_key
      secretText: APIKEY


build:
  -
    setup_proj_deps : true
    scripts:
      - "pwsh.exe -ExecutionPolicy ByPass -File .\\cicdscripts\\SetupHost.ps1"
      - "pwsh.exe -ExecutionPolicy ByPass -File .\\cicdscripts\\BuildSolution.ps1"      

soc2:
  white_source:    
    skip: false
    fail_on_audit_failure: true
    team: Dynamo
    project_name: "PackageManagerClient"
    hidden_email_list: dynamo_ws_access
    third_party_lib_paths:
      - "third_party"
      - "src/packages"
      - "%COMMON_TOOLS_DIR%"

deployment:
    -
        type: customized
        scripts:
            - "pwsh.exe -ExecutionPolicy ByPass -File .\\cicdscripts\\ExecuteContainerDeploy.ps1"
            - "pwsh.exe -ExecutionPolicy ByPass -File .\\cicdscripts\\PostDeploy.ps1"